const sites = [
  "https://www.concur.com",
  "https://www.concur.ca",
  "https://www.concur.ca/fr",
  "https://www.concur.com.mx",
  "https://www.concur.com.br",
  "https://www.concur.com.ar",
  "https://www.concur.co.za",
  "https://www.concur.ae",
  "https://www.concur.co.uk",
  "https://www.concur.fr",
  "https://www.concur.de",
  "https://www.concur.it",
  "https://www.concur.nl",
  "https://www.concur.se",
  "https://www.concur.dk",
  "https://www.concur.fi",
  "https://www.concur.be",
  "https://www.concur.es",
  "https://www.concur.no",
  "https://www.concur.com.au",
  "https://www.concur.cn",
  "https://www.concur.com.hk",
  "https://www.concur.co.in",
  "https://www.concur.co.jp",
  "https://www.concur.kr",
  "https://www.concur.com.sg",
  "https://www.concur.tw",
];

export default sites;
